## DNA Isolation from Blood

Blood draws are an easy way for our lab to get genetic information from the non-human primates that are currently under study.  Ideally, these samples would be processed for DNA isolation immediately.  However, many of the blood samples that we have in our blood library are up to 10 years old, and for some samples it can be difficult to generate high yielding, clean DNA samples.  While not all of our older blood samples are compromised, there were enough failed or low yielding samples over time among multiple technicians to justify troubleshooting the DNA isolation procedure.

In order to minimize negative results, existing protocols for isolating leukocyte (white blood cell) and for isolating DNA using leucoctyes (buffy coat) have been modified.  Leukocytes are isolated with BD Pharm Lyse buffer, which are then used with the Gentra Puregene Blood Kit for DNA isolation.  While this could be done with other kits such as the Flexigene DNA Kit, the Gentra Puregene Blood Kit was chosen for its protein precipitation step.  Many kits use a protease such as Proteinase K to digest proteins, but Gentra Puregene uses a Protein Precipitation solution that seems to be more effective for our leukocyte samples and has a longer lasting shelf life.
 
### Materials and Experiment Preparation

* Human and non-human primate blood contains different pathogens, and could be dangerous to your health if handled improperly.  Before handling blood samples for the first time discuss these implications with the lab, and attend a Bloodborne Pathogens training program if necessary.  Always wear Personal Protective Equipment (PPE) and work with blood under a certified biosafety cabinet.
*	This procedure is designed to isolate DNA following leukocyte isolation from 1250 µL of whole blood in 15 mL tubes.  With this method you can isolate 1-2 samples at a time.  
*	Ideally, fresh blood samples (< 1 hour old) are used, but this method was generated using 10 year old cryopreserved samples, which are more likely to produce lower yields of DNA at a lower quality.
*	Each sample will require at least 6 mL of PBS/FBS wash buffer, 12.5 mL of PLB, 3 15 mL tubes, 70% EtOH, and Isopropanol.
*	Proper blood samples should produce around 100 µL of leukocytes.
*	Additional equipment used in this protocol includes an aspiration bottle system, Pasteur pipettes, a serological pipettor/pipettes, and a centrifuge and shaker table that can handle 15 mL tubes.  It’s also important to use molecular grade water free of DNase, RNase, Protease, and Nuclease.
*	Dilute solutions of Pharm Lyse Buffer (PLB) and Phosphate Buffered Saline (PBS) to a concentration of (1X).  Assuming an initial concentration of (10X) and an end volume less than 50 mL, the below values can be used for the dilution.

    > C~i~ = [10X];   C~f~ = [1X];   V~f~ = 45 mL  
    > **V~i~** = ?;   **V~H2O~** = ?  
    > **V~i~** = ([1X]) \* (45 mL) / ([10X])  
    > **V~i~** = 4.5 mL  
    > **V~H2O~** = 45 mL - 4.5 mL = 40.5 mL
    
*	Using (1X) PBS, create a solution of PBS and 2% Fetal Bovine Serum (FBS) to use as a wash buffer.  For simplicity mix 10 mL of PBS with 200 µL of FBS in a 15 mL tube.  (**Note:**  *FBS is commonly used as a cell culture reagent.  Do not obtain any FBS by yourself.  To prevent potential sources of cell culture contamination ask someone who does cell culture work to aliquot 10 mL of FBS for your personal use.  FBS is also sensitive to freeze-thaw cycles, so it’s important to create 1 mL working solutions to prevent FBS denaturation.*)
*	Prepare aliquots of 70% ethanol and Isopropanol.

### Pharm Lyse Buffer

1.  Collect blood in heparinized (green cap) or EDTA (Purple cap) coated vial.
2.	Bring (1X) PLB and blood vial (if frozen) to room temperature.  By placing the blood vial in a 15 mL tube, the PLB and the blood can be brought to temperature using a heating bath.
3.	After the blood thaws, place it on ice (optional).
4.	Transfer no more than 1250 µl of the blood to a 15 mL conical tube.  When removing the stopper from the vials, slowly ease the stopper past the rim to prevent spraying or aerosolization of blood caused by quick pressure release.
5.	Add 12.5 mL of (1X) PLB buffer to the blood.
6.	GENTLY vortex for 5 seconds. 
7.	Place in dark cabinet for 10-15 minutes.
8.	Centrifuge 200g -500g for 5 min.
9.	Discard the supernatant using a Pasteur pipette and aspirator system.
10.	Wash the leukocytes 2-3 times to remove any trace of red blood cells.
    a.	Wash the sample and gently re-suspending the pellet with 1X PBS, 2% FBS.  
    b.	Centrifuge at 350g for 5 min.
    c.	Discard the supernatant using a Pasteur pipette and aspirator system.
11.	Estimate the volume of leukocytes.  A good yield is between 50 µL and 100 µL, however, lower yields may occur.
12.	Re-suspend the pellet (cells) in a small volume (1 mL) of 1X PBS, 2% FBS, and then proceed with further cleaning or DNA isolation.  Skip this step if isolating DNA immediately.

### Gentra Puregene Blood Kit

(**Note:**  This method uses the *DNA Purification from Buffy Coat* protocol, which can be found in the Gentra Puregene Handbook that comes with the Gentra Puregene Blood Kit.  Buffy coat refers to the layer of leukocytes and platelets that appear when processing fresh blood via centrifugation.)

1.	Prepare reagents and equipment according to the protocol.
2.	Use Table 2 in the Gentra Puregene Handbook for scaling reagent volumes.  A yield of 50 µL to 100 µL of leukocytes usually corresponds to 3.5 * 10^6^ total number of white blood cells.  If the DNA purity (A~260~/A~280~;  A~260~/A~230~) or concentration is irregular, then try adjusting the reagent volumes using the same ratios from Table 2.
3.	Do not use the aspirator bottle system when you are washing the DNA pellet, because it is easily removed with the wash solution.
4.	Continue with the Gentra Puregene, DNA Purification from Buffy Coat protocol.
5.	If lysed and washed properly, the leukocytes should not contain any residual red blood cells, so the RBC Lysis steps at the beginning of the protocol can be skipped.  Additionally, the optional RNA removal step can be skipped.
6.	Using the Nanodrop, measure the concentration and purity of your DNA.
