# Dilutions

  Please memorize the C~i~V~i~ = C~f~V~f~ formula for making dilutions.  It is used in many of the experiments that we do in this lab.  The core concept and formula is M = CV (Mass = Concentration * Volume).  In a dilution the mass of the solute does not change (e.g. M~i~ = M~f~).  
  It's very important that you do this math ahead of time after you've designed your experiment.  Make sure that you have enough of your solution at each stage of your dilution.  For example, if you are diluting your primers for a PCR and you only have 125 ul of 200 uM, then there is a maximum amount of 100 uM solution that you will be able to make:

> C~i~ = 200 uM, V~i~ = 125 ul, C~f~ = 100 uM, V~f~ = The maximum amount of 100 uM solution that we can make.
V~f~ = (200 uM) * (125 uL) / 100 uM = 600 uL

So the maximum amount of 100 uM solution that we will be able to make is 600 uL.
  
## Stock vs Psuedo-stock vs Working Solutions {#reagent_scheme}
 
It's wise to create stock and working solutions in order preserve your reagents and to prevent contamination.  The stock solution is the solution of the largest volume and/or concentration.  Generally, the stock solution is kept in the manufacturer's container for easy identification and to prevent contamination.  A working solution is an aliquot of the stock solution that is used in an experiment.  In some situations it might be a good idea to make a psuedo-stock solution (at half the concentration of the stock) before a working solution is made.  This is an extra step that not only prevents frequent freeze thaw cycles of your stock solution, but it also lowers the number of times that you have to pipette into and out of the stock solution.

