# Designing Primers {#design_primers}

Designing primers is a good way to get familiar with DNA as a sequence.  It will also help you understand some of the chemistry that's involved with a PCR reaction.  There are plenty of guides out there, but [this one](https://genome.ucsc.edu/cgi-bin/hgPcr?hgsid=676475057_IWRKULUdIcAeQLDoEcOLx9JixaFC) is one of our favorites.  In order to design a primer you must first have a DNA sequence of interest.  This can be accomplished in several ways.  99% of the time you have a target gene of interest.  So if you can find the NCBI accession number or GI number (deprecated for future annotations), then you can get your sequence of interest.  Some common tools to fascilitate this process include [Primer3Plus](http://primer3plus.com/cgi-bin/dev/primer3plus.cgi), [NCBI's PrimerBlast](https://www.ncbi.nlm.nih.gov/tools/primer-blast/), [UCSC's Blat](https://genome.ucsc.edu/cgi-bin/hgBlat), and [UCSC's In-Silico PCR](https://genome.ucsc.edu/cgi-bin/hgPcr?hgsid=676475057_IWRKULUdIcAeQLDoEcOLx9JixaFC).  UCSC and NCBI also have a wide array of useful tools that are worth exploring.

## Ordering Primers {#order_primers}

Once the primers have been designed, verify them with someone else in the lab and then consult Dr. Vallender.  Generally, he will order the primers himself from Integrated DNA Technologies.  IDT is another great resource for learning more about molecular biology.

## Stock Solution {#stock_solution}

(*Note:*  _Please read this section along with the [noteworthy techniques](#noteworthy_techniques) section and [dilution](#dilutions) section if you've never resuspended a primer before._)

The lyophilized (dried) primers are ususally delivered in a cardboard envelope.  IDT has this to say about lypholized/dry oligos compared to resuspended oligos:

>Oligos that are resuspended in TE buffer (10 mM Tris pH 8.0, 0.1 mM EDTA; such as IDTE), are more stable than dry oligos at room temperature or 4°C.  Oligos that are stored in water are the least stable. However, at 4°C, oligos stored under all of these conditions are stable for at least 60 weeks.  For long term storage, whether oligos are dried down, or resuspended in non-DEPC treated water or TE buffer (10 mM Tris pH 8.0, 0.1 mM EDTA; such as IDTE), it's optimal to store them frozen, at -20°C.  Also, it is ideal to store oligos in the dark. Exposure to UV light should be avoided, and ambient lab light should be minimized, particularly for some types of modified oligos. Please see the Technical Report, Oligonucleotide Stability Study, for data on oligonucleotide storage and a more thorough explanation.

Before [resuspending](#primer_dilutions) the primers you should note a few things:

1.  The stock solution is the most concentrated form of your primer so be careful with it.
2.  Careful not to contaminate the stock tube.
    * Always spin down the lypholized primer, *before opening the tube*.
    * Always spin down the resupended primer.
    * Always use a new tip.
3. Don't contaminate the stock tube.  (Do you see what I did there?)
4. Resuspend primer stock solutions to *100uM* or *200uM*, create pseudo-working solutions if applicable, create working solutions, and then freeze them all down.

**For a 200 uM stock solution:**

>Dissolve fresh primer with the 5X volume of water as its concentration to get a 200 uM concentration.
>
>For example, for 25 nmoles (nanomoles) of primer, add 125 ul of water. This will give you a concentration of 0.0002 M or 0.2 mM or 200 uM.
>
>(25 nmoles/L) (x moles/125 * 10-6 L) = .0002 mole/L = 0.0002 M = 0.2 mM = 200 uM

**For a 100 uM stock or psuedo-working solution:**

>Dissolve fresh primer with the 10X volume of water as its concentration to get a 100 uM concentration.
>
>For example, for 25 nmoles (nanomoles) of primer, add 250 ul of water. This will give you a concentration of 0.0001 M or 0.1 mM or 100 uM.
>
>(25 nmoles/L) (x moles/250 * 10-6 L) = .0001 mole/L = 0.0001 M = 0.1 mM = 100 uM

(**Note**:  _If this is confusing to you, then try using the [primer resuspension calculator](https://www.idtdna.com/calc/resuspension/) by IDT._)

5. If it's available use TE buffer to store the stock solutions.
6. For most cases use no more than 1/3 of the volume of your stock tubes to create the first working solution.

## Working Solution {#working_solution}

Working solutions are exactly what they sound like.  The solutions that you will be using during an experiment.  Generally, the working solution will be at *10uM*, but they can be adjusted for various resons or in special protocols.  When making working solutions it's important not to contaminate the stock tube.  If you want to get fancy, then you can make several dilution steps for your primers to reduce freeze/thawing of the stock solution (e.g. 200uM stock, 100uM psuedo-working, and 10uM working).
