# Getting started {#getting_started} 


## Our Lab's Culture

## Lab Attire

## Important Skills

## Keeping a Lab Notebook

## Best Practices {#best_practices} 

In a molecular genetics lab, there are many techniques that you can use in order to efficiently preform experiments in a scientifically repeatable way.  Many of these techniques are simple tips and tricks of the trade.  Some of them are skills that take time to build.  And others require additional reagents, consumables, or equipment.  Some are redundant, and will be unnecessary for every use case.  However, I would suggest carefully reading this section, and using some common sense to determine which practices are right for your situation.

### Preventing Contamination {#contamination}

When performing any type of experiment, it's always important to prevent cross contamination.  For cell culture experiments, it's bacterial or fungal cells, and for many molecular experiments it's DNA or RNA contamination from other samples.  Reagent contamination is another dangerous and often overlooked type of cross contamination that can affect current and future experiments.  This is why it's necessary to make working solutions of your stock reagents.  It may seem like it takes a lot of time, but in the end working solutions save time and money that would otherwise be spent troubleshooting an experiment that is behaving abnormally.

Having a pre-measured or pre-diluted working solution is the best way to prevent mathematical, pipetting, and contamination errors.  Working solutions also help with the calculations that need to be made before an experiment takes place, which saves valuable time.  If and when mistakes are made, contaminated reagents can easily be discarded and new working solutions can be retrieved from storage.  (**Always check the lab's inventory before discarding a sample/reagent.  Some samples and reagents have limited availability**.)

### Centrifugation {#spinning_down}

When working through a protocol, gentle centrifugation of various tubes or plates is usually necessary.  Air bubbles, liquid on the sides, or liquid on the top of your plates or tubes is not only annoying, but it also frequently leads to contamination, evaporation, improper volume, or improper concentration.  These issues can be avoided by additionally checking to make sure your plates or tubes are sealed before centrifugation.  If you end up contaminating some of your reagents, then clean your workspace thoroughly and dispose of anything that you suspect to be contaminated (**check your inventory first**).  Proceed by creating more aliquots with the pseudo-stock solution or retrieving another working solution from storage.

### Pipetting

Pipetting is one of the very basic techniques that you will need to know for most labs.  This lab in particular relies heavily on pipetting for molecular and cell culture experiments.  So developing good pipetting skills is vital for success and efficiency.

There are many special techniques that you can use in order to pipette like a seasoned professional.  Gilson has a very comprehensive manual that I would suggest going over.  It's mentioned in [this](https://bitesizebio.com/344/17-ways-to-stop-pipetting-errors-ruining-your-experiments/) Bitesize Bio blog post on pipetting techniques.

While preference often plays a huge role in what pipette tips are purchased, some specialized tips have use-cases that go beyond user preference.  For instance, some pipettors can only be used with certain tips, and some tips can only be used with certain pipettors.  Other special properties, such as being sterile (rnase, dnase, and protease free), or having filtered tips, also makes a difference when selecting pipette tips.  Filtered tips are useful for preventing pipettor contamination.  They are vital in certain situations such as DNA or RNA isolation and cell culture.  In these situations it's usually important to utilize filter tips that are also dnase/rnase/protease free.

## Preparing for an Experiment

Always prepare your experiment ahead of time, whether it's the night before or a few hours before you need to begin.

### Reading

Always read through the manufacturer's and/or proprietary protocols that you will be using at least a day in advance, and then review the protocol before preparing your experiment.  You may also want to read alternative instructions or online forums in order to see what other scientists are doing to solve the same problems.

### Calculating

Human error is also more frequently introduced, when attempting to *quickly* work out math problems.  Before starting an experiment, always carefully work through any calculations.  It's never a good idea or feeling to begin doing math that takes 10 minutes in the middle of a time sensitive protocol that only allows for 5 minutes of extra time.  Dilutions for example need to be done before the experiment so that you have an adequate amount of time and working solution for your protocol.

### Pre-Cleaning

Tidying up or organizing your workspace before and after an experiment helps keep things in order, which in turn helps you focus on your assay vs. finding the right pipettor underneath your stack of protocols.  Clearing your workspace also gives you the opportunity to use 70% ethanol to clean the workbench and the equipment.  This step is important to remove any unwanted debris, whether it be tissue, DNA, RNA, skin cells (your own or someone else's), chemicals, and bacteria.  Cleaning in this manner also makes the lab bench a safe place for everyone's experiments, lab notebooks, and personal safety.

## During the Experiment

### Testing

If it's the first time your are running an experiment it's always a good idea to do a test run.  For most cases there should be some extra sample materials that you can use in order to test your abilities.  This is especially important if you are low on sample material for your real experiment!  Ask someone in the lab if they know where to find extra samples or reagents.

### Timing

Timing is always important.  Whether you are doing an experiment for the first time or you are trying to optimize an experiment, it's a wise idea to time yourself.  Knowing the time will help you plan experiments in the future.

Cell culture and animal model experiments take days/weeks/months of time to execute so careful planning is needed in order to optimize the time of everyone involved.  The same is needed for molecular experiments, but usually only on an hourly/daily/weekly time schedule.

### Writing

It's always important to take notes during a protocol.  Some labs are very strict about lab notebooks, and how they are kept.  This lab is not as strict, but we still find it very important to keep an informal lab notebook for each type of experiment.  In some instances we have simply kept a record using a notepad.

### Post-Cleaning

Tidying up or organizing your workspace before and after an experiment helps keep things in order, which in turn helps you focus on your assay vs. finding the right pipettor underneath your stack of protocols.  Clearing your workspace also gives you the opportunity to use 70% ethanol to clean the workbench and the equipment.  This step is important to remove any unwanted debris, whether it be tissue, DNA, RNA, skin cells (your own or someone else's), chemicals, and bacteria.  Cleaning in this manner also makes the lab bench a safe place for everyone's experiments, lab notebooks, and personal safety.
