# Molecular: Noteworthy Techniques {#noteworthy_techniques} 

In molecular genetics labs there are many techniques that you can use in order to efficiently preform experiments in a scientifically repeatable way.  Many of these techniques are simple tips and tricks of the trade.  Some of them are skills that take time to build.  And others require additional reagents, consumables, or equipment.  Some are redundant, and will be unnecessary for every usecase.  However, I would suggest carefully reading this section, and using some common sense to determine which practices are right for your situation.

## Things to Consider

### Contamination {#contamination}

It's import for any experiment to prevent cross contamination of any kind.  With cell culture it's bacteria, and with many molecular experiments it's DNA/RNA contamination from other samples.  It's also highly important to prevent the contamination of reagents, which could affect the current and all future experiments that use said reagent.  This is why it's necessary to make working solutions of your stock reagents.  It might take some time, but it beats having to troubleshoot why an experiment has gone wrong.  

Working solutions also help you pre-calculate the amount of reagent you have for any one experiment.  That way you don't find out your low on attractene in the middle of a cell culture experiment or that you don't have enough qPCR primer to finish your master mixes.

### Centrifugation {#spinning_down}

When working through an experiment or protocol, gentle centrifugation of various tubes/plates is always necessary.  Air bubbles, liquid on the sides, and liquid on the top is not only annoying, but it also frequently leads to contamination or inproper volume/concentration measurements.  Remember to always spin your tubes down so that you get reliable results.  If you end up contaminating some of your reagents, then clean your workspace thoroughly and dispose of anything that you suspect to be contaminated (check your inventory first).  Proceed by creating more aliquots with the psuedo-stock solution.

### Pipetting

Pipetting is one of the very basic techniques that you will need to know for most labs.  This lab in particular relies heavily on pipetting for molecular and cell culture experiments.  So developing good pipetting skills is vital for success and efficiency.

There are many special techniques that you can use in order to pipet like a seasoned professional.  Gilson has a very comprehensive manual that I would suggest going over.  It's mentioned in [this](https://bitesizebio.com/344/17-ways-to-stop-pipetting-errors-ruining-your-experiments/) Bitesize Bio blog post on pipetting technique.

While preference often plays a huge role in what pipette tips are purchased, there are many types of specialized tips available on the market.  Some pipettors can only be used with certain tips, and some tips can only be used with certain pipettors.  Some pipettor tips have special properties, such as being sterile (rnase, dnase, and protease free), or having filtered tips.  Filtered tips are useful for preventing pipettor contamination.  They are vital in certain situations such as DNA/RNA isolation and cell culture.  In these situations it's usually important to utilize dnase/rnase/protease free tips that also have a filter.

## Preparing for an Experiment

Always prepare your experiment ahead of time, wheather it's the night before or a few hours before you need to begin.

### Reading

Always read through the manufacturer's and/or proprietary protocols that you will be using at least a day in advance, and then review the protocol before preparing your experiment.  You may also want to read alternative instruction or online forums in order to see what other scientists are doing to solve the same problems.

### Calculating

Before doing any experiment always work through calculations that may be needed prior to an experiment.  It's never a good idea or feeling to begin doing math that takes 20 minutes in the middle of a time sensitive protocol that only allows for 5 minutes of extra time.  Human error is also more frequently introduced, when attempting to *quickly* work out math problems.  

Dilutions for example need to be done before the experiment so that you have an adequate amount of working solution for your protocol.  More on dilutions can be found in the appendix.

### Pre-Cleaning

Tidying up or organizing your workspace before and after an experiment helps keep things in order, which in turn helps you focus on your assay vs. finding the right pipettor underneath your stack of protocols.  Clearing your workspace also gives you the opportunity to use 70% ethanol to clean the workbench and the equipment.  This step is important to remove any unwanted debris, wheather it be tissue, DNA, RNA, skin cells (your own or someone elses), chemicals, and bacteria.  Cleaning in this manner also makes the lab bench a safe place for everyone's experiments, lab notebooks, and personal safety.

## During the Experiment

### Testing

If it's the first time your are running an experiment it's always a good idea to do a test run.  For most cases there should be some extra sample materials that you can use in order to test your skills.  This is especially important if you are low on sample material for your real experiment!  Ask someone in the lab if they know where some extra samples or reagents can be found.

### Timing

Timing is always important.  Wheather you are doing an experiment for the first time or you are trying to optimize an experiment, it's a wise idea to time yourself.  Knowing the time will help you plan experiments in the future.

Cell culture and animal model experiments take days/weeks/months of time to execute so careful planning is needed in order to optimize the time of everyone involved.  The same is needed for molecular experiments, but usually only on an hourly/daily/weekly time schedule.

### Writing

It's always important to record things during your experiment.  Some labs are very strict about lab notebooks, and how they are kept.  This lab is not as strict, but we still find it very important to keep an informal lab notebook for each type of experiment.  In some instances we have simply kept a record using a notepad.

### Post-Cleaning

Tidying up or organizing your workspace before and after an experiment helps keep things in order, which in turn helps you focus on your assay vs. finding the right pipettor underneath your stack of protocols.  Clearing your workspace also gives you the opportunity to use 70% ethanol to clean the workbench and the equipment.  This step is important to remove any unwanted debris, wheather it be tissue, DNA, RNA, skin cells (your own or someone elses), chemicals, and bacteria.  Cleaning in this manner also makes the lab bench a safe place for everyone's experiments, lab notebooks, and personal safety.

