# Molecular: Genotyping {#molecular_genotyping}

Genotyping is useful when we would like to compare the genetics of multiple animals.  Some of the genotyping methods that we use in our lab include:

* [PCR](#pcr_protocol)
  * [Designing Primers](#design_primers)
  * Thermocycler Setup
  * RFLP - Restriction Fragment Length Polymorphism
* Electrophoresis
  * Gel
  * [Capillary](#capillary_electrophoresis)
* [qPCR](#qpcr_protocol)
* DNA sequencing

## Polymerase Chain Reaction (PCR)

Watch this [cool video](https://www.youtube.com/watch?v=2KoLnIwoZKU) of PCR to get a better understanding of the process.  To actually start a PCR experiment, several things need to take place:

1. [DNA has to be isolated](#dna_isolation) and verified from the target organisms.
2. Primers have to be designed, ordered, resuspended, and diluted to the proper concentrations.
3. The experiment has to be [designed, and the workspace has been prepared](#noteworthy_techniques).
4. A program has to be created on the [thermocycler](#thermocycler), and the QiAxcel has been prepared for a gel read.

### Primers

Primers are the cornerstone of any PCR.  Many [vendors sell primers](#quartzy) that already work with a particular gene.  However, many scientists have to design their own primers, because the gene of interest is not available from a commercial distributor.  After the primers have been obtained, they need to be resuspended in DNAse free molecular grade water.  This is called the "stock solution".  A "working solution(s)" should also be made to preserve the stock solution.

## Electrophoresis

Electrophoresis is the process of moving charged particles (in our case DNA) in a fluid or gel under the influence of an electric field.  To analyze a target gene with electrophoresis, PCR is preformed first to amplify the DNA concentration of the target gene.  The end goal of electrophoresis is to effectively estimate the number of base pairs in the DNA samples that are being tested in order to identify the alleles that are present.

Generally, we use the QIAxcel for capillary electrophoresis, which is much faster than gel electrophoresis.  However, we also have the reagents and equipment to run a classic gel using ethidium bromide.  Check out this [video](https://www.youtube.com/watch?v=sSKls2kNC4U&list=PLe4H-Q82aBZDV_E7q5-lUAPPkcfVgOquZ&index=5) to get a better understanding of how to run a manual gel.

### Analyzing Gels

More to come...

## Quantitative/Real-Time PCR

(**Note**:  _For our lab we use Roche's Universal Proble Library (preferred), and SYBR Green.  The qPCR protocol is written for the UPL system._)

Quantitative PCR (qPCR) or Real Time PCR (rtPCR) is an older technique that has been largely replaced with _Next Generation Sequencing (NGS)_ also known as _High Throughput Sequencing (HTS)_ for some applications.  Nevertheless, qPCR is still used for certain experiments and/or for validating NGS/HTS results.  qPCR machines work the same as traditional thermocyclers, except they contain photodetectors for measuring fluorescent signals.  During the DNA amplification process the fluorescence signal increases indicating an increase in DNA concentration.  Using special software the qPCR machine can accurately calculate the starting concentration of the target gene.  Check out this [video](https://www.youtube.com/watch?v=YhXj5Yy4ksQ) to get a better understanding of qPCR.  Check [here](https://www.youtube.com/watch?v=DH7o9Df5_50) for a more detailed explanation.

To actually start a qPCR experiment in order to measure RNA expression, several things need to take place:

1. [RNA has to be isolated](#rna_isolation).
2. cDNA libraries must be created from RNA samples.
3. Primers and Probes have to be designed, ordered, resuspended, and diluted to the proper concentrations. 
4. The experiment has to be [designed, and the workspace has been prepared](#noteworthy_techniques).
5. A program has to be created on the [LightCycler 96](#).

## DNA Sequencing {#dna_sequencing}

More to come...
