# Molecular: Genotyping {#molecular_genotyping}

Genotyping is useful when we would like to compare the genetics of multiple animals.  Some of the genotyping methods that we use in our lab can be found in [this article](https://en.wikipedia.org/wiki/Genotyping).

## Polymerase Chain Reaction (PCR)

Watch the PCR video below to get a better understanding of the process.

<iframe width="720" height="480" src="https://www.youtube.com/embed/2KoLnIwoZKU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

To actually start a PCR experiment, several things need to take place:

1. [DNA has to be isolated](#dna_isolation_protocol) and verified from the target organisms.
2. Primers have to be designed, ordered, resuspended, and diluted to the proper concentrations.
3. The experiment has to be [designed, and the workspace has been prepared](#molecular_best_practices).
4. A program has to be created on the [thermocycler](#thermocycler).
5. The QiAxcel has to be prepared for a gel read.

### Primers

Primers are the cornerstone of any PCR.  Many [vendors sell primers](#quartzy) that already work with a particular gene.  However, many scientists have to design their own primers, because the gene of interest is not available from a commercial distributor.  After the primers have been obtained, they need to be resuspended in DNAse free molecular grade water.  This is called the "stock solution".  A "working solution(s)" should also be made to preserve the stock solution.

### Restriction Fragment Length Polymorphism (RFLP)

RFLP is a genotyping technique that exploits and simultaneously identifies genetic variations in homologous DNA sequences.  Restriction enzymes are used to break DNA into 2 or more fragments that are then analyzed with gel electrophoresis.  Different alleles can be detected when the associate polymorphisms cause the restriction fragments to be differing sizes.

### Thermocycler

A thermocycler is a machine that amplifys DNA using PCR.  The thermocycler systematically raises and lowers the temperature of the holding block using a [Peltier](https://en.wikipedia.org/wiki/Thermoelectric_effect#Peltier_effect) device.  The end user must program each step into the thermocycler, based on the methods of the PCR reaction.  Generally, a thermocycler program will take the PCR reaction through 4 different steps:

1. Inital Denaturation
2. Amplification (30-40 cycles)
3. Final Extension
4. Cooling

The amplification cycles in step two can be further broken down:

1. Denaturation
2. Annealing
3. Extension

While the temperatures and timing of each step may change with each PCR reaction, most of the time these basic steps will be worked into the thermocycler program.

## Electrophoresis

Electrophoresis is the process of moving charged particles (in our case DNA) in a fluid or gel under the influence of an electric field.  To analyze a target gene with electrophoresis, PCR is preformed first to amplify the DNA concentration of the target gene.  The end goal of electrophoresis is to effectively estimate the number of base pairs in the DNA samples that are being tested in order to identify the alleles that are present.

Generally, we use the QIAxcel for capillary electrophoresis, which is much faster than gel electrophoresis.  However, we also have the reagents and equipment to run a classic gel electrophoresis experiment using ethidium bromide.  Check out the video below to get a better understanding of how to run a manual gel.

<iframe width="720" height="480" src="https://www.youtube.com/embed/sSKls2kNC4U?list=PLe4H-Q82aBZDV_E7q5-lUAPPkcfVgOquZ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Analyzing Gels

Analyzing gels can help give you different pieces of information.  If your PCR experiment has been implemented with newly designed primers, then a gel can help validate that your PCR is working correctly.  Running PCR experiments with positive and negative DNA controls is a good way to confirm that new primers are working.  Strange PCR results generated by new primers may indicate that your experiment needs to be manipulated.  This could mean that you need to redisign your primers, new reagents need to be made, or you need to alter your PCR conditions.  

After you have designed and validated your PCR experiment with positive and negative controls, you are then able to run your PCR experiment on untested DNA.  Measuring the bands of the PCR experiment will tell you if the organism of interest is a heterozygous dominant, heterozygous recessive, or homozygous.  If different alleles of a gene are simply a SNP, gels aren't usually precise enough to measure this difference.  In this case a restriction enzyme could be used to break apart the gene at the location of the SNP.  That way you can determine which version of the allele is present based on the absene or appearance of multiple DNA bands.

## DNA Sequencing {#dna_sequencing}

We generally outsource DNA sequencing in our lab to the Genomics Core for whole genomes, or through third party services for sequencing single genes via Sanger sequencing.  Visual analysis can be done for homologous strands of DNA by first aligning the sequences of interest, and then using special software to look at each base pair in order to identify SNPs or other mutations.  Using this type of observation method is usually preserved to single gene sequences.  For analysis of whole chromosomes or genomes, we usually use a more advanced bioinformatics approach in order to obtain more holistic and objective results.

## Relevant Protocols

* [PCR](#pcr_protocol)
    * [Designing Primers](#design_primers)
    * [Troubleshooting PCR](#troubleshooting_pcr)
    * [Capillary Electrophoresis](#capillary_electrophoresis)
