# Molecular: Phenotyping {#phenotyping}

In this lab "phenotyping"" generally refers to the various forms of gene expression analysis that we do.  What this means for molecular work is usually some form of RNA isolation and quantification.  For microbiome projects 16S rRNA genes (DNA) are used to identify and quantify various microbial communities.  Behavioral phenotyping is usually gathered in an adjacent lab, and is analyzed alongside phenotyping/genotyping data that is associated with the same samples or specimen.

## Quantitative/Real-Time PCR

(**Note**:  _For our lab we use Roche's Universal Proble Library (preferred), and SYBR Green.  The qPCR protocol is written for the UPL system._)

Quantitative PCR (qPCR) or Real Time PCR (rtPCR) is an older technique that has been largely replaced with _Next Generation Sequencing (NGS)_ also known as _High Throughput Sequencing (HTS)_ for some applications.  Nevertheless, qPCR is still used for certain experiments and/or for validating NGS/HTS results.  qPCR machines work the same as traditional thermocyclers, except they contain photodetectors for measuring fluorescent signals.  During the DNA amplification process the fluorescence signal increases indicating an increase in DNA concentration.  Using special software the qPCR machine can accurately calculate the starting concentration of the target gene.  Check out this [video](https://www.youtube.com/watch?v=YhXj5Yy4ksQ) to get a better understanding of qPCR.  Check [here](https://www.youtube.com/watch?v=DH7o9Df5_50) for a more detailed explanation.

To actually start a qPCR experiment in order to measure RNA expression, several things need to take place:

1. [RNA has to be isolated](#rna_isolation).
2. cDNA libraries must be created from RNA samples.
3. Primers and Probes have to be designed, ordered, resuspended, and diluted to the proper concentrations. 
4. The experiment has to be [designed, and the workspace has been prepared](#molecular_best_practices).
5. A program has to be created on the [LightCycler 96](#).

## RNA Sequencing

More to come...

## Single-Cell RNA Sequencing

More to come...

## 16S rRNA Gene (DNA) Sequencing

More to come...
