# Stable Cell Line Generation

## Lentiviral Transduction to Generate a Stable Cell Line

### Lentiviral Transduction using Positive Control (GFP) for determining optimal MOI for transduction efficiency

Day 1: Seed the cells at 50-70% confluency in 1 well of a 24 well plate.

Day 2: Aspirate medium from the well. Add the * predetermined amount of lentiviral particles (MOI=2) to the well. Add 1 mL of media with serum (FBS) to the well. Incubate for 18-20 hours in the incubator.

Day 3: Remove the medium containing the lentiviral particles from the well. Add 1 mL of fresh growth medium with serum to the well.

Day 5: Observe cells under a fluorescent microscope to determine the transduction efficiency of the positive control.

### Lentiviral Transduction using a reporter (CRE, SRE, AP-1, NFkB) for establishing a stable cell line

Day 1: Seed the cells at 50-70% confluency in 1 well of a 24 well plate.

Day 2: Aspirate medium from the well. Add the * predetermined amount of lentiviral particles (MOI=2) to the well. Add 1 mL of media with serum (FBS) to the well. Incubate for 18-20 hours in the incubator.

Day 3: Aspirate the medium containing the lentiviral particles from the well. Add 1 mL of fresh growth medium with serum (FBS) and pen -strep (if necessary) to the well.

STOP ►►► AFTER REMOVAL OF THE PARTICLES, ALLOW AT LEAST 3 DAYS FOR THE REPORTER TO BECOME INTEGRATED INTO THE HOST CELL’S GENOME!!!

Day 4: Observe cells under a light microscope to determine if the cells are confluent enough to be split. Split the cells and plate them in one well of a 6-well
plate.

Day 6: Observe cells under a light microscope to determine if the cells are confluent enough to be split (if not, push each subsequent step back a day). Split the cells and plate them in a 100 mm dish.

Day 7: Add fresh growth medium ( WITHOUT PEN-STREP ) and the optimal concentration of geneticin to the cells. Never add geneticin on the same day that you plate the cells.

Day 8 & Beyond: Check the cells daily ( if possible) to ensure that cell death is occurring and that viable cells are still growing. Add fresh media and geneticin to the cells every 3 days. Once the cells are confluent in a 100 mm plate, trypsinize them using 1 mL of trypsin. Then re-plate the cells in 2-100 mm plates. From there, continue to select the cells using geneticin for 2-3 weeks. Before freezing the cells, test for reporter expression. Lastly, freeze the cells using Recovery Freezing medium.

### Multiplicity of Infection: Determining the amount of lentiviral particles to add

The transduction efficiency of Cignal Lenti reporters varies significantly for different cell type. It is important to determine the Multiplicity of Infection (MOI), which is the number of transducing lentiviral particles per cell, required to get desired transduction efficiency for each new cell type. The MOI is typically adjusted by increasing or decreasing the amount of virus added per well to a series of wells containing the same number of cells.

I recommend testing the Cignal Lenti Positive Control (CLS-PCG) at an **MOI of 2** in order to establish at least a baseline of what an optimal transduction efficiency would be. This will give an idea (based on the cell line) of what MOI to use for transducing the reporter. I usually use a **MOI of 2 (1 or 3 can be used)** for transduction of the Lenti-CRE reporter and other reporter assays.

#### To calculate

_Multiplicity of Infection (MOI)_ = Number of transducing units (TU) deposited in a well
Number of target cells present in that well

_Total transducing units needed per well (TU)_ = (Total number of cells per well) x (Desired
MOI)

_Total mL of lentiviral particles to add to each well_ = Total TU needed per well
TU/mL reported on Certificate of Analysis
